[package]
name = "magic-num"
version = "0.1.0"
authors = ["Cristian Filipescu <cfilipescu@epicblockchain.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
